INSERT INTO USER_DETAIL(ID,BIRTH_DATE,NAME) VALUES (10001,current_date(),'Ranganathan');
INSERT INTO USER_DETAIL(ID,BIRTH_DATE,NAME) VALUES (10002,current_date(),'Sultan');
INSERT INTO USER_DETAIL(ID,BIRTH_DATE,NAME) VALUES (10003,current_date(),'FilmDirector');
INSERT INTO USER_DETAIL(ID,BIRTH_DATE,NAME) VALUES (10004,current_date(),'Kamalhasan');
INSERT INTO USER_DETAIL(ID,BIRTH_DATE,NAME) VALUES (10005,current_date(),'Rajini');
INSERT INTO USER_DETAIL(ID,BIRTH_DATE,NAME) VALUES (10006,current_date(),'Director');

INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES (20001,'Learn People',10001);
INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES (20002,'Learn Computer',10001);
INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES (20003,'Learn History',10001);
INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES (20004,'Learn Physics',10001);
INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES (20005,'Learn Chemistry',10001);

INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES (20011,'Learn People',10002);
INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES (20012,'Learn Computer',10003);
INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES (20013,'Learn History',10004);
INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES (20014,'Learn Physics',10005);
INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES (20015,'Learn Chemistry',10006);
